#!/bin/sh

set -e

tests/standalone.sh

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

cd $WORKDIR
cat <<EOF > libidntest.c
#include <stringprep.h>

int main(void)
{
  if (!stringprep_check_version (STRINGPREP_VERSION))
    return 1;

  return 0;
}
EOF

gcc -o libidntest libidntest.c `pkg-config --cflags --libs libidn`
echo "PASS: gcc"
[ -x libidntest ]
./libidntest
echo "PASS: run"
man -P cat stringprep_check_version
echo "PASS: man"
